name: learn-github-actions
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: run CI
        run: |
          npm install
          npm run lint
          npm run build
